version: '3.4'

networks:
  frontend:
  backend:

services:
  event_catalog_api_SVC:
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    image: event_catalog_api_img
    environment:
      DatabaseServer: event_mssqlserver_SVC
      DatabaseName: EventLiteCatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:5678
    ports:
      - "5678:80"
    container_name: event_catalog_api_CNTR
    networks:
      - backend
      - frontend
    depends_on:
      - event_mssqlserver_SVC


      
  event_cart_api_SVC:
    build:
      context: .\EventCartApi
      dockerfile: Dockerfile
    image: event_cart_api_img
    environment:
      IdentityUrl: http://169.254.139.65:6789
      ConnectionString: event_basket_data_SVC
    ports:
      - "8910:80"
    container_name: event_cart_api_CNTR
    networks:
      - backend
      - frontend
    depends_on:
      - event_basket_data_SVC
      - event_token_server_SVC

  event_mssqlserver_SVC:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1440:1433"
    container_name: event_mssqlserver_CNTR
    networks:
      - backend

  event_token_server_SVC:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: event_token_server_img
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:1337
    ports:
      - "6789:80"
    container_name: event_token_server_CNTR
    networks:
      - backend
      - frontend
    depends_on:
      - event_mssqlserver_SVC


  event_webmvc_SVC:
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    image: event_webmvc_img
    environment:
      EventCatalogApiUrl: http://event_catalog_api_SVC
      IdentityUrl: http://169.254.139.65:6789
      CallBackUrl: http://localhost:1337
      CartUrl: http://event_cart_api_SVC
      ASPNETCORE_ENVIRONMENT: Development
    ports:
     - "1337:80"
    container_name: event_webmvc_CNTR
    networks:
      - frontend
    depends_on:
      - event_catalog_api_SVC
      - event_cart_api_SVC
      - event_token_server_SVC

  event_basket_data_SVC:
    image: redis
    container_name: event_basket_data_CNTR
    ports:
      - "5704:6379"
    networks:
      - backend